import { Model, DataTypes } from 'sequelize'
import db from './_instance'

class Vertek extends Model {}

/** @type {import('sequelize').ModelAttributes<Vertek, import('sequelize').Optional<any, never>>} */
const attributes = {
  id: {
    allowNull: false,
    primaryKey: true,
    autoIncrement: true,
    type: DataTypes.INTEGER,
  },

  UsulanId: DataTypes.INTEGER,
  SasaranId: DataTypes.INTEGER,
  status: DataTypes.INTEGER,
  keterangan: DataTypes.TEXT,
  namaPupr: DataTypes.STRING,
  jabatanPupr: DataTypes.STRING,
  nipPupr: DataTypes.STRING,
  telponPupr: DataTypes.STRING,
  namaSnvt: DataTypes.STRING,
  jabatanSnvt: DataTypes.STRING,
  nipSnvt: DataTypes.STRING,
  telponSnvt: DataTypes.STRING,
  namaPejKabKota: DataTypes.STRING,
  jabatanPejKabKota: DataTypes.STRING,
  nipPejKabKota: DataTypes.STRING,
  telponPejKabKota: DataTypes.STRING,
  dataLapangan1: DataTypes.TEXT,
  dataLapangan2: DataTypes.TEXT,
  dataLapangan3: DataTypes.TEXT,
  dataLapangan4: DataTypes.TEXT,
  dataLapangan5: DataTypes.TEXT,
  dataLapangan6: DataTypes.TEXT,
  dataLapangan7: DataTypes.TEXT,
  dataLapangan8: DataTypes.TEXT,
  dataLapangan9: DataTypes.TEXT,
  dataLapangan10: DataTypes.TEXT,
  dataLapangan11: DataTypes.TEXT,
  dataLapangan12: DataTypes.TEXT,
  dataLapangan13: DataTypes.TEXT,
  dataLapangan14: DataTypes.TEXT,
  dataLapangan15: DataTypes.TEXT,
  dataLapangan16: DataTypes.TEXT,
  dataLapangan17: DataTypes.TEXT,
  dataLapangan18: DataTypes.TEXT,
  dataLapangan19: DataTypes.TEXT,
  dataLapangan20: DataTypes.TEXT,
  dataLapangan21: DataTypes.TEXT,
  dataLapangan22: DataTypes.TEXT,
  dataLapangan23: DataTypes.TEXT,
  //rusun
  tglSurvei: DataTypes.DATE,
  surveyor: DataTypes.STRING,
  proposalAsli: DataTypes.BOOLEAN,
  legalitasLahan: DataTypes.BOOLEAN,
  sesuaiRTRW: DataTypes.BOOLEAN,
  sesuaiMasterPlan: DataTypes.BOOLEAN,
  kondisi: DataTypes.STRING,
  perkerasanJalan: DataTypes.STRING,
  sumberListrik: DataTypes.STRING,
  sumberAir: DataTypes.STRING,
  jarakKepusatKegiatan: DataTypes.STRING,
  kondisiTanah: DataTypes.STRING,
  kelayakanTeknis: DataTypes.BOOLEAN,
  //rusus
  namaLokasiDetail: DataTypes.TEXT,
  titikKoordinat: DataTypes.TEXT,
  peruntukan: DataTypes.TEXT,
  tglVertek: DataTypes.DATE,
  statusLahan: DataTypes.TEXT,
  rtrw: DataTypes.TEXT,
  luasLahan: DataTypes.TEXT,
  kondisiLahan: DataTypes.TEXT,
  kondisiJalanAkses: DataTypes.TEXT,
  jauhLahanDariJalanUtama: DataTypes.TEXT,
  sumberAirBersih: DataTypes.TEXT,
  sumberPenerbanganDanJarakGardu: DataTypes.TEXT,
  aksesSaluranPembuangan: DataTypes.TEXT,
  groundJarak: DataTypes.TEXT,
  sitePlant: DataTypes.TEXT,
  jenisTanah: DataTypes.TEXT,
  tipologiPermukaanTanah: DataTypes.TEXT,
  rawanBencana: DataTypes.TEXT,
  catatan: DataTypes.TEXT,
  fileFoto: DataTypes.TEXT,
  fileVertek: DataTypes.TEXT,
}

Vertek.init(attributes, {
  sequelize: db.sequelize,
  modelName: 'Vertek',
  tableName: 'verteks',
})

export default Vertek
